import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import hoyLop from "../assets/lop.jpg";
import {
  GrInstagram,
  GrFacebookOption,
  GrFacebook,
  GrLinkedin,
  GrLinkedinOption,
  GrMail,
} from "react-icons/gr";
import Tabs from "../components/Tabs";
import Featured from "../components/Featured";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HOY LOP!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <article className={styles.left}>
          <h1>hoy Lop!</h1>
          <section>
            <div className={styles.imageContainer}>
              <Image src={hoyLop} alt="" placeholder="blur" />
              <h2>all about me</h2>
            </div>
          </section>
        </article>
        <article className={styles.right}>
          <section className={styles.socials}>
            <GrInstagram className={styles.icon} />
            <GrFacebookOption className={styles.icon} />
            <GrLinkedin className={styles.icon} />
            <GrMail className={styles.icon} />
          </section>

          <Tabs />

          <Featured />
        </article>
      </main>
    </div>
  );
}
